#!/bin/bash
# Part of check_oxidized
# Copyright (C) 2021, Jan-Philipp Litza <jpl@plutex.de>.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -eu
set -o pipefail
shopt -s lastpipe

SERVER="$1"
NODE="$2"

if ! RESULT="$(curl -sL "http://${SERVER}/nodes.json" | jq -r 'map(select(.name == "'"${NODE,,}"'"))[0] | [.status, .time, if .last then "yes" else "no" end] | join("|")')" || [ -z "$RESULT" ]; then
  echo "UNKNOWN: Failed fetching backup status"
  exit 3
fi

if [ "$RESULT" = "||no" ]; then
  echo "UNKNOWN: Node not configured for backup"
  exit 3
fi

echo "$RESULT" | IFS="|" read -r STATUS TIME LAST

if [ "$STATUS" = "success" ]; then
  echo "OK: last backup at ${TIME} was successful"
  exit 0
elif [ "$LAST" = "no" ]; then
  echo "WARNING: No backup tries since startup"
  exit 1
else
  echo "CRITICAL: status=${STATUS} time=${TIME}"
  exit 2
fi
